# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Lessons\Su2022\Residue\src\myWin\my.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 828)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.k_label = QtWidgets.QLabel(self.centralwidget)
        self.k_label.setGeometry(QtCore.QRect(50, 40, 20, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.k_label.setFont(font)
        self.k_label.setObjectName("k_label")
        self.m_label = QtWidgets.QLabel(self.centralwidget)
        self.m_label.setGeometry(QtCore.QRect(50, 100, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.m_label.setFont(font)
        self.m_label.setObjectName("m_label")
        self.m_value = QtWidgets.QLabel(self.centralwidget)
        self.m_value.setGeometry(QtCore.QRect(727, 108, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.m_value.setFont(font)
        self.m_value.setObjectName("m_value")
        self.proceed_button = QtWidgets.QPushButton(self.centralwidget)
        self.proceed_button.setGeometry(QtCore.QRect(830, 32, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.proceed_button.setFont(font)
        self.proceed_button.setObjectName("proceed_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(830, 102, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.k_value = QtWidgets.QLabel(self.centralwidget)
        self.k_value.setGeometry(QtCore.QRect(727, 40, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.k_value.setFont(font)
        self.k_value.setObjectName("k_value")
        self.m_bar = QtWidgets.QSlider(self.centralwidget)
        self.m_bar.setGeometry(QtCore.QRect(90, 108, 631, 22))
        self.m_bar.setOrientation(QtCore.Qt.Horizontal)
        self.m_bar.setObjectName("m_bar")
        self.k_bar = QtWidgets.QSlider(self.centralwidget)
        self.k_bar.setGeometry(QtCore.QRect(90, 40, 631, 22))
        self.k_bar.setOrientation(QtCore.Qt.Horizontal)
        self.k_bar.setObjectName("k_bar")
        
        # self.segmentation_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        # self.segmentation_graphicsView.setGeometry(QtCore.QRect(40, 210, 867, 556))
        # self.segmentation_graphicsView.setObjectName("segmentation_graphicsView")
        midLayout=QHBoxLayout()
        self.segmentation_graphicsView=QTableWidget()
        midLayout.addWidget(self.segmentation_graphicsView)

        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(40, 172, 867, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_button.setFont(font)
        self.select_button.setObjectName("select_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.k_label.setText(_translate("MainWindow", "k"))
        self.m_label.setText(_translate("MainWindow", "m"))
        self.m_value.setText(_translate("MainWindow", "30"))
        self.proceed_button.setText(_translate("MainWindow", "Proceed"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.k_value.setText(_translate("MainWindow", "100"))
        self.select_button.setText(_translate("MainWindow", "Select Image"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
